spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jobsearch
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  application:
    name: job-search
server.servlet.context-path: /${spring.application.name}
